/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as DenunciarRouteImport } from './routes/denunciar'
import { Route as AcompanharRouteImport } from './routes/acompanhar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PTokenRouteImport } from './routes/p.$token'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const DenunciarRoute = DenunciarRouteImport.update({
  id: '/denunciar',
  path: '/denunciar',
  getParentRoute: () => rootRouteImport,
} as any)
const AcompanharRoute = AcompanharRouteImport.update({
  id: '/acompanhar',
  path: '/acompanhar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PTokenRoute = PTokenRouteImport.update({
  id: '/p/$token',
  path: '/p/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acompanhar': typeof AcompanharRoute
  '/denunciar': typeof DenunciarRoute
  '/painel': typeof PainelRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/p/$token': typeof PTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acompanhar': typeof AcompanharRoute
  '/denunciar': typeof DenunciarRoute
  '/painel': typeof PainelRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/p/$token': typeof PTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acompanhar': typeof AcompanharRoute
  '/denunciar': typeof DenunciarRoute
  '/painel': typeof PainelRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/p/$token': typeof PTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acompanhar'
    | '/denunciar'
    | '/painel'
    | '/sitemap.xml'
    | '/p/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acompanhar'
    | '/denunciar'
    | '/painel'
    | '/sitemap.xml'
    | '/p/$token'
  id:
    | '__root__'
    | '/'
    | '/acompanhar'
    | '/denunciar'
    | '/painel'
    | '/sitemap.xml'
    | '/p/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcompanharRoute: typeof AcompanharRoute
  DenunciarRoute: typeof DenunciarRoute
  PainelRoute: typeof PainelRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  PTokenRoute: typeof PTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/denunciar': {
      id: '/denunciar'
      path: '/denunciar'
      fullPath: '/denunciar'
      preLoaderRoute: typeof DenunciarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acompanhar': {
      id: '/acompanhar'
      path: '/acompanhar'
      fullPath: '/acompanhar'
      preLoaderRoute: typeof AcompanharRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$token': {
      id: '/p/$token'
      path: '/p/$token'
      fullPath: '/p/$token'
      preLoaderRoute: typeof PTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcompanharRoute: AcompanharRoute,
  DenunciarRoute: DenunciarRoute,
  PainelRoute: PainelRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  PTokenRoute: PTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
